from googleapiclient.discovery import build

from gpaw.services.gsuite import GoogleSuite

class GoogleCalendar(GoogleSuite):
    """The service object responsible for providing an interface with Google Calendar.

    :param auth: An OAuth credential object generated by the oauth2client library, gets passed to the super's constructor.

    """
    def __init__(self, auth):
        GoogleSuite.__init__(self, auth)
        self.service = build('calendar', 'v3', credentials=self.auth).events()

    def Create(self):
        print('create event')
 