from googleapiclient.discovery import build

from gpaw.services.gsuite import GoogleSuite

class GoogleTasks(GoogleSuite):
    """The service object responsible for providing an interface with Google Tasks.
    
    :param auth: An OAuth credential object generated by the oauth2client library, gets passed to the super's constructor.
    
    """
    def __init__(self, auth):
        GoogleSuite.__init__(self, auth)
        self.service = build('tasks', 'v1', credentials=self.auth).tasks()

    def Create(self):
        print('create task')