# -*- coding: utf-8 -*-

from googleapiclient.discovery import build

"""
gpaw.services

This module contains the service classes that are responsible for executing functionalities of GSuite services.
"""

# from .exceptions import NotAuthorized


class GoogleSuite(object):
    """Base class for all other Google Suite service classes.

    :param: auth: An OAuth credential object generated by the oauth2client library.

    """
    def __init__(self, auth):
        self.auth = auth

class GoogleCalendar(GoogleSuite):
    """The service object responsible for providing an interface with Google Calendar.

    :param auth: An OAuth credential object generated by the oauth2client library, gets passed to the super's constructor.

    """
    def __init__(self, auth):
        GoogleSuite.__init__(self, auth)
        self.service = build('calendar', 'v3', credentials=self.auth).events()

    def Create(self):
        print('create event')

class GoogleSheets(GoogleSuite):
    """The service object responsible for providing an interface with Google Sheets.
    
    :param auth: An OAuth credential object generated by the oauth2client library, gets passed to the super's constructor.
    
    """
    def __init__(self, auth):
        GoogleSuite.__init__(self, auth)
        self.service = build('sheets', 'v4', credentials=self.auth).spreadsheets()

    def Read(self):
        print('read spreadsheet')

    def Write(self):
        print('write spreadsheet')
    

class GoogleTasks(GoogleSuite):
    """The service object responsible for providing an interface with Google Tasks.
    
    :param auth: An OAuth credential object generated by the oauth2client library, gets passed to the super's constructor.
    
    """
    def __init__(self, auth):
        GoogleSuite.__init__(self, auth)
        self.service = build('tasks', 'v1', credentials=self.auth).tasks()

    def Create(self):
        print('create task')

